version: '3'
services:
  webapp:
    build: .
    ports: 
      - "80:80"
    environment: 
      - ASPNETCORE_ENVIRONMENT='Production'
    depends_on: 
      - ravendb
      - eventstore
    links: 
      - ravendb
      - eventstore
    restart: always
  ravendb:
    restart: always
    volumes:
      - "./ravedb_data:/opt/RavenDB/Server/RavenData"
  eventstore:
    restart: always
    volumes:
      - "./eventstore_data:/var/lib/eventstore"
  