version: '3'
services:
  webapp:
    build: .
    ports: 
      - "80:80"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on: 
      - ravendb
      - eventstore
    links: 
      - ravendb
      - eventstore
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.60'
          memory: 2000M
        reservations:
          cpus: '0.50'
          memory: 1000M
  ravendb:
    restart: always
    volumes:
      - "./ravedb_data:/opt/RavenDB/Server/RavenData"
  eventstore:
    restart: always
    volumes:
      - "./eventstore_data:/var/lib/eventstore"
  