version: '3'
services:
  ravendb:
    image: ravendb/ravendb
    ports:
      - "8080:8080"
      - "38888:38888"
    environment:
      - RAVEN_ARGS='--Setup.Mode=None'
      - RAVEN_Security_UnsecuredAccessAllowed='PrivateNetwork'
  eventstore:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
