version: '3'
services:
  webapp:
    build: .
    ports: 
      - "8081:80"
    depends_on: 
      - ravendb
      - eventstore
    links: 
      - ravendb
      - eventstore
  ravendb:
    image: ravendb/ravendb
    ports:
      - "8080:8080"
      - "38888:38888"
    environment:
      - RAVEN_ARGS='--Setup.Mode=None'
      - RAVEN_Security_UnsecuredAccessAllowed='PrivateNetwork'
  eventstore:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
